theme: jekyll-theme-minimal
title: Byoungho Son
logo: /asset/img/byhoson-photo1.jpg
description: Ph.D student at POSTECH
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll/scholar
